"""Allow for * import from dolfin with some degree of control."""

import dolfin

from dolfin import (
    Mesh,
    Constant,
    Parameters,
    lhs,
    rhs,
    Expression,
    Function,
    VectorSpaceBasis,
    LinearVariationalProblem,
    inner,
    grad,
    LinearVariationalSolver,
    Measure,
    assemble,
    system,
    TrialFunction,
    TestFunction,
    PETScKrylovSolver,
    LUSolver,
    TrialFunctions,
    TestFunctions,
    FunctionAssigner,
    Timer,
    MeshFunction,
    FiniteElement,
    FunctionSpace,
    MixedElement,
    dx,
    VectorFunctionSpace,
    DirichletBC,
    solve,
    parameters,
    NonlinearVariationalSolver,
    NonlinearVariationalProblem,
    KrylovSolver,
    derivative,
    Vector,
    as_backend_type,
    UnitSquareMesh,
    project,
    split,
    dP,
    Form,
    UnitCubeMesh,
    PointIntegralSolver,
    RL1,
    ln,
    exp,
    pi,
    ge,
    conditional,
    UnitIntervalMesh,
    RK4,
    ERK4,
    mpi_comm_world,
    MPI,
)

from dolfin.cpp.function import (
    GenericFunction,
)


try:
    import dolfin_adjoint
except:
    dolfin_adjoint = None


__all__ = [
    "dolfin",
    "Mesh",
    "Constant",
    "Parameters",
    "lhs",
    "rhs",
    "Expression",
    "Function",
    "VectorSpaceBasis",
    "LinearVariationalProblem",
    "inner",
    "grad",
    "LinearVariationalSolver",
    "Measure",
    "assemble",
    "system",
    "TrialFunction",
    "TestFunction",
    "PETScKrylovSolver",
    "LUSolver",
    "TrialFunctions",
    "TestFunctions",
    "FunctionAssigner",
    "Timer",
    "MeshFunction",
    "FiniteElement",
    "FunctionSpace",
    "MixedElement",
    "dx",
    "GenericFunction",
    "VectorFunctionSpace",
    "DirichletBC",
    "solve",
    "parameters",
    "NonlinearVariationalSolver",
    "NonlinearVariationalProblem",
    "KrylovSolver",
    "derivative",
    "Vector",
    "dolfin_adjoint",
    "as_backend_type",
    "UnitSquareMesh",
    "project",
    "split",
    "dP",
    "Form",
    "UnitCubeMesh",
    "PointIntegralSolver",
    "RL1",
    "ln",
    "exp",
    "pi",
    "ge",
    "conditional",
    "UnitIntervalMesh",
    "RK4",
    "ERK4",
    "mpi_comm_world",
    "MPI",
]
