#!/bin/sh

# Script to generate documentation for the beatadjoint module
#
# Dependencies:
# * beatadjoint
# * sphinx-apidoc (sphinx-doc.org)
#
# Marie E. Rognes (meg@simula.no), 2013

echo "This script generates the documentation for beat-adjoint."
echo "Make sure to run this from the top-level beatadjoint directory: "
echo "  ./scripts/generate-doc"
echo "Press return to continue."
read x
echo ""

sphinx-apidoc -o doc -H beatadjoint -A beatadjoint-authors -V 0.1 beatadjoint/
export PYTHONPATH=$PYTHONPATH:`pwd`
cd doc
make html

echo ""
echo "Documentation successfully generated."
echo "A good starting point is doc/_build/html/index.html"
