#!/bin/sh

# Script to generate documentation for the cbcbeat module
#
# Dependencies:
# * cbcbeat
# * sphinx-apidoc (sphinx-doc.org)
#
# Marie E. Rognes (meg@simula.no), 2013

echo "This script generates the documentation for beat-adjoint."
echo "Make sure to run this from the top-level cbcbeat directory: "
echo "  ./scripts/generate-doc"
echo "Press return to continue."
read x
echo ""

sphinx-apidoc -o doc -H cbcbeat -A cbcbeat-authors -V 0.1 cbcbeat/
export PYTHONPATH=$PYTHONPATH:`pwd`
cd doc
make html

echo ""
echo "Documentation successfully generated."
echo "A good starting point is doc/_build/html/index.html"
