#!/usr/bin/env python

from gotran2.codegeneration.oderepresentation import ODERepresentation
from beatadjoint.gotran2cellmodel import CellModelGenerator
from gotran2.model import load_ode


def main(filename):
    """
    Create a beat cell model from a gotran model
    """

    # Load Gotran model
    ode = load_ode(filename)

    # Create an ODE representation
    oderepr = ODERepresentation(ode, keep_intermediates=False)

    # Create a Beat Cell model code generator
    cell_gen = CellModelGenerator(oderepr)

    f = open(filename.replace(".ode", "")+".py", "w")
    f.write(cell_gen.generate())

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) != 2:
        raise RuntimeError("Expected 1 gotran file argument")

    main(sys.argv[-1])
